/* New drawings in the same manner as design/reference-c.html: material (wood, stone, iron, brass, glass, parchment,
   wax, chalk) and light, seeded randomness, generated by functions. The reference functions in art.js are not edited;
   per-professor door props are layered on top of them here. */
import {rng, shade, r1, door, metal, stud, pinnedCard, EXTRAS, tornRect, CX, SPRING, RO, BOTTOM, RL} from './art.js';

const esc = s => String(s).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function shadow(cx, cy, rx, ry, o = .45){ return `<ellipse cx="${r1(cx)}" cy="${r1(cy)}" rx="${rx}" ry="${ry}" fill="#000" opacity="${o}"/>`; }
function pin(x, y){ return `<circle cx="${r1(x)}" cy="${r1(y)}" r="2.6" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".5"/><circle cx="${r1(x - .8)}" cy="${r1(y - .8)}" r=".8" fill="#fff" opacity=".6"/>`; }
function nail(x, y){ return `<circle cx="${x}" cy="${y}" r="2.4" fill="#0E1011"/><circle cx="${x}" cy="${y}" r="1.7" fill="url(#g-iron)"/><circle cx="${x - .6}" cy="${y - .6}" r=".6" fill="#9AA3A8" opacity=".8"/>`; }
function star4(x, y, s){ return `M${r1(x)} ${r1(y - s)} Q${r1(x)} ${r1(y)} ${r1(x + s)} ${r1(y)} Q${r1(x)} ${r1(y)} ${r1(x)} ${r1(y + s)} Q${r1(x)} ${r1(y)} ${r1(x - s)} ${r1(y)} Q${r1(x)} ${r1(y)} ${r1(x)} ${r1(y - s)} Z`; }

/* ============================================================ door props on the leaf (swing open with it) */

/* Snape: a barred speaking grille; the green of the dungeon shows faintly through it */
function grille(){
  const x = CX - 21, y = 150, w = 42, h = 40; let s = '';
  s += `<rect x="${x - 4}" y="${y - 4}" width="${w + 8}" height="${h + 8}" rx="2" fill="#000" opacity=".45" transform="translate(1.5 2.5)"/>`;
  s += `<rect x="${x - 4}" y="${y - 4}" width="${w + 8}" height="${h + 8}" rx="2" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".8"/>`;
  s += `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#040605"/>`;
  s += `<rect class="glow" x="${x}" y="${y}" width="${w}" height="${h}" fill="url(#g-grille)"/>`;
  s += `<path d="M${x} ${y + 1} h${w}" stroke="#000" stroke-width="3" opacity=".6"/>`;
  for (let k = 1; k < 5; k++){ const vx = x + k * w / 5;
    s += `<rect x="${r1(vx - 1.7)}" y="${y}" width="3.4" height="${h}" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".5"/><path d="M${r1(vx - .8)} ${y + 1} v${h - 2}" stroke="#7A8389" stroke-width=".6" opacity=".7"/>`; }
  s += `<rect x="${x}" y="${y + h / 2 - 1.6}" width="${w}" height="3.2" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".5"/>`;
  [[x - 1.5, y - 1.5], [x + w + 1.5, y - 1.5], [x - 1.5, y + h + 1.5], [x + w + 1.5, y + h + 1.5]].forEach(p => { s += stud(p[0], p[1], metal('iron')); });
  return s;
}

/* McGonagall: a polished brass kick plate, screwed on, scuffed by impatient boots */
function kickPlate(){
  const y = 465, h = 21, x = CX - RL; let s = '';
  s += `<rect x="${x}" y="${y}" width="${2 * RL}" height="${h}" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".9"/>`;
  s += `<rect x="${x}" y="${y + .8}" width="${2 * RL}" height="1.2" fill="#FFF1C2" opacity=".55"/><rect x="${x}" y="${y + h - 2}" width="${2 * RL}" height="2" fill="#6A5218" opacity=".5"/>`;
  s += `<path d="M${x + 22} ${y + 9} l26 3 M${x + 70} ${y + 13} l18 -2 M${x + 104} ${y + 7} l30 4" stroke="#6A5218" stroke-width=".7" opacity=".45"/>`;
  s += `<path d="M${x + 30} ${y + 6} l14 2 M${x + 112} ${y + 14} l20 1" stroke="#FFF1C2" stroke-width=".6" opacity=".5"/>`;
  for (let k = 0; k < 6; k++){ const sx = x + 7 + k * (2 * RL - 14) / 5, sy = y + h / 2;
    s += `<circle cx="${r1(sx)}" cy="${sy}" r="2.1" fill="#8E6A1E" stroke="#6A5218" stroke-width=".5"/><path d="M${r1(sx - 1.4)} ${sy + .9} l2.8 -1.8" stroke="#3A2A08" stroke-width=".6"/>`; }
  return s;
}

/* Lupin: a pinned lunar calendar, the full moon ringed in red ink */
function moonPath(cx, cy, r, f, waxing){
  if (f <= 0.02 || f >= 0.98) return '';
  const rx = r1(r * Math.abs(1 - 2 * f));
  const top = `${r1(cx)} ${r1(cy - r)}`, bot = `${r1(cx)} ${r1(cy + r)}`;
  if (waxing) return `M${top} A${r} ${r} 0 0 1 ${bot} A${rx} ${r} 0 0 ${f < .5 ? 0 : 1} ${top} Z`;
  return `M${top} A${r} ${r} 0 0 0 ${bot} A${rx} ${r} 0 0 ${f < .5 ? 1 : 0} ${top} Z`;
}
function moonChart(){
  const x = 88, y = 154, w = 74, h = 46; let s = `<g transform="rotate(2.5 ${x + w / 2} ${y + h / 2})">`;
  s += `<rect x="${x + 1.5}" y="${y + 2.5}" width="${w}" height="${h}" fill="#000" opacity=".35"/><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#DCCDA6"/>`;
  s += `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="none" stroke="#8A7A55" stroke-width=".5"/>`;
  s += `<text x="${x + w / 2}" y="${y + 13}" text-anchor="middle" font-family="'IM Fell English', Georgia, serif" font-style="italic" font-size="8.5" fill="#2A2118">Phases of the Moon</text>`;
  const phases = [[0, 1], [.25, 1], [.5, 1], [.75, 1], [1, 1], [.75, 0], [.5, 0]];
  phases.forEach((p, k) => { const cx = x + 8 + k * 9.6, cy = y + 25, r = 3.6;
    s += `<circle cx="${r1(cx)}" cy="${cy}" r="${r}" fill="${p[0] >= 1 ? '#F3EBD2' : '#2A2118'}" stroke="#2A2118" stroke-width=".6"/>`;
    const lit = moonPath(cx, cy, r, p[0], p[1]); if (lit) s += `<path d="${lit}" fill="#F3EBD2"/>`;
    if (p[0] >= 1) s += `<ellipse cx="${r1(cx)}" cy="${cy}" rx="6.2" ry="5.6" fill="none" stroke="#9A1F1F" stroke-width="1" transform="rotate(-12 ${r1(cx)} ${cy})"/><path d="M${r1(cx - 4)} ${cy + 8} q4 2 8 -1" stroke="#9A1F1F" stroke-width=".8" fill="none"/>`;
  });
  s += `<path d="M${x + 7} ${y + 37} h30 M${x + 7} ${y + 41} h22 M${x + 44} ${y + 37} h22" stroke="#2A2118" stroke-width=".7" opacity=".55"/>`;
  s += pin(x + w / 2, y + 4) + '</g>';
  return s;
}

/* Moody: a warning card among the bands */
function vigilance(){ return pinnedCard(CX - 62, 370, 84, 36, -3, ['CONSTANT', 'VIGILANCE!'], false); }

/* Umbridge: a framed decree hung from a nail by a pink ribbon */
function decree(){
  const x = 66, y = 374, w = 76, h = 52, nx = x + w / 2, ny = 362; let s = '';
  s += `<path d="M${nx} ${ny} L${x + 6} ${y + 2} M${nx} ${ny} L${x + w - 6} ${y + 2}" stroke="#D9618A" stroke-width="1.4"/>`;
  s += `<rect x="${x + 2}" y="${y + 3}" width="${w}" height="${h}" fill="#000" opacity=".35"/>`;
  s += `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#E7A9BC" stroke="#B4577A" stroke-width=".9"/>`;
  s += `<rect x="${x + 3}" y="${y + 3}" width="${w - 6}" height="${h - 6}" fill="none" stroke="#C9A24A" stroke-width="1"/>`;
  s += `<rect x="${x + 6}" y="${y + 6}" width="${w - 12}" height="${h - 12}" fill="#F3E8D0"/>`;
  s += `<text x="${x + w / 2}" y="${y + 16}" text-anchor="middle" font-family="'IM Fell English SC', Georgia, serif" font-size="7" fill="#7A2A45">Educational</text>`;
  s += `<text x="${x + w / 2}" y="${y + 25}" text-anchor="middle" font-family="'IM Fell English SC', Georgia, serif" font-size="8.5" fill="#7A2A45">Decree</text>`;
  s += `<path d="M${x + 12} ${y + 31} h${w - 24} M${x + 12} ${y + 35} h${w - 30} M${x + 12} ${y + 39} h${w - 27}" stroke="#2A2118" stroke-width=".6" opacity=".55"/>`;
  s += `<circle cx="${x + w - 15}" cy="${y + h - 11}" r="3.6" fill="#B4234A"/><circle cx="${x + w - 16}" cy="${y + h - 12}" r="1.2" fill="#fff" opacity=".35"/>`;
  s += `<path d="M${nx} ${ny} q-8 -6 -9 0 q1 6 9 0 Z M${nx} ${ny} q8 -6 9 0 q-1 6 -9 0 Z" fill="#F6C7D6" stroke="#B4577A" stroke-width=".7"/><circle cx="${nx}" cy="${ny}" r="1.8" fill="#E58EAD" stroke="#B4577A" stroke-width=".6"/>`;
  return s;
}

/* Dumbledore: a night-sky fanlight in the arch head, brass glazing bars radiating like the sun knocker's rays */
function fanlight(){
  const r = RL - 6, cy = SPRING, R = rng(907); let s = '';
  s += `<path d="M${CX - r} ${cy} A${r} ${r} 0 0 1 ${CX + r} ${cy} Z" fill="url(#g-night)"/>`;
  s += `<path d="M${CX - r} ${cy} A${r} ${r} 0 0 1 ${CX + r} ${cy} Z" fill="url(#g-nightglow)" class="glow"/>`;
  let n = 0;
  while (n < 26){
    const x = CX - r + R() * 2 * r, y = cy - R() * r;
    if ((x - CX) ** 2 + (y - cy) ** 2 > (r - 5) ** 2) continue;
    if ((x - CX) ** 2 + (y - 170) ** 2 < 26 ** 2) continue;
    if ((x - (CX + 40)) ** 2 + (y - 158) ** 2 < 12 ** 2) continue;
    if (n % 3 === 0) s += `<path class="tw" style="animation-delay:-${r1(R() * 4)}s;animation-duration:${r1(2.4 + R() * 2.6)}s" d="${star4(x, y, 1.8 + R() * 1.6)}" fill="#F7E7B0"/>`;
    else s += `<circle class="tw" style="animation-delay:-${r1(R() * 4)}s;animation-duration:${r1(3 + R() * 3)}s" cx="${r1(x)}" cy="${r1(y)}" r="${r1(.45 + R() * .6)}" fill="#fff" opacity=".85"/>`;
    n++;
  }
  const mx = CX + 40, my = 158;
  s += `<circle cx="${mx}" cy="${my}" r="12" fill="#F3E2A6" opacity=".12" class="glow"/>`;
  s += `<path d="M${mx} ${my - 6.5} A6.5 6.5 0 1 0 ${mx} ${my + 6.5} A4.6 6.5 0 1 1 ${mx} ${my - 6.5} Z" fill="#F3E2A6"/>`;
  for (let a = 15; a <= 165; a += 30){ const t = a * Math.PI / 180, ex = CX + r * Math.cos(t), ey = cy - r * Math.sin(t);
    s += `<path d="M${CX} ${cy} L${r1(ex)} ${r1(ey)}" stroke="#6A5218" stroke-width="2.8"/><path d="M${CX} ${cy} L${r1(ex)} ${r1(ey)}" stroke="#D9BC6A" stroke-width="1.1"/>`; }
  s += `<path d="M${CX - r} ${cy} A${r} ${r} 0 0 1 ${CX + r} ${cy}" fill="none" stroke="#6A5218" stroke-width="4"/><path d="M${CX - r} ${cy} A${r} ${r} 0 0 1 ${CX + r} ${cy}" fill="none" stroke="#D9BC6A" stroke-width="1.6"/>`;
  s += `<rect x="${CX - RL}" y="${cy - 1}" width="${2 * RL}" height="6" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".8"/>`;
  return s;
}
/* Dumbledore: a phoenix tail feather pinned to the door */
function feather(){
  const L = 100, R = rng(313); let s = `<g transform="translate(64 446) rotate(-39)">`;
  s += `<ellipse class="glow" cx="52" cy="0" rx="58" ry="15" fill="#F2B24C" opacity=".16"/>`;
  s += `<path d="M2 1.5 L${L} 1.5" stroke="#000" stroke-width="2" opacity=".3"/>`;
  s += `<path d="M8 0 C22 -11 62 -13 ${L} 0 C62 9 22 8.5 8 0 Z" fill="url(#g-phoenix)"/>`;
  for (let x = 14; x < L - 6; x += 3.6){ const t = (x - 8) / (L - 8), up = 11 * Math.sin(Math.PI * Math.pow(t, .85)), dn = 8 * Math.sin(Math.PI * Math.pow(t, .85));
    s += `<path d="M${r1(x)} 0 L${r1(x + 6)} ${r1(-up * .92)} M${r1(x)} 0 L${r1(x + 6)} ${r1(dn * .9)}" stroke="#5E0F0F" stroke-width=".45" opacity="${r1(.3 + R() * .3)}"/>`; }
  s += `<path d="M${L - 26} -4 C${L - 16} -6 ${L - 6} -3 ${L} 0 C${L - 8} 3 ${L - 18} 4 ${L - 26} 2.5 Z" fill="#FFE2A0" opacity=".55"/>`;
  s += `<path d="M10 -2 q-4 -5 -1 -8 M12 2 q-3 5 0 8 M15 -3 q-2 -6 2 -9" stroke="#C83A1F" stroke-width=".8" fill="none" opacity=".8"/>`;
  s += `<path d="M-4 0 L${L} 0" stroke="#8A6A44" stroke-width="1.6"/><path d="M-4 -.4 L${L - 4} -.4" stroke="#F7EED8" stroke-width=".8"/>`;
  s += pin(0, 0) + '</g>';
  return s;
}

/* Slughorn: a gilt-edged invitation with a purple ribbon */
function invitation(){
  const x = 60, y = 376, w = 88, h = 40; let s = `<g transform="rotate(2 ${x + w / 2} ${y + h / 2})">`;
  s += `<rect x="${x + 1.5}" y="${y + 2.5}" width="${w}" height="${h}" fill="#000" opacity=".35"/><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#F4EBD3"/>`;
  s += `<rect x="${x + 2.5}" y="${y + 2.5}" width="${w - 5}" height="${h - 5}" fill="none" stroke="#C5A253" stroke-width="1.1"/><rect x="${x + 4.5}" y="${y + 4.5}" width="${w - 9}" height="${h - 9}" fill="none" stroke="#C5A253" stroke-width=".4"/>`;
  s += `<path d="M${x} ${y + 15} L${x + 15} ${y} L${x + 21} ${y} L${x} ${y + 21} Z" fill="#6B2A72"/><path d="M${x} ${y + 16.5} L${x + 16.5} ${y}" stroke="#C48ACB" stroke-width=".6" opacity=".7"/>`;
  s += `<text x="${x + w / 2 + 4}" y="${y + 20}" text-anchor="middle" font-family="'IM Fell English', Georgia, serif" font-style="italic" font-size="12" fill="#4A1F52">Slug Club</text>`;
  s += `<text x="${x + w / 2 + 4}" y="${y + 31}" text-anchor="middle" font-family="'IM Fell English', Georgia, serif" font-size="7.5" fill="#5B4A33">by invitation only</text>`;
  s += pin(x + w / 2, y + 4) + '</g>';
  return s;
}

/* a glint that slides across the nameplate when the door comes to the centre */
const GLINT = `<g clip-path="url(#plate-clip)"><rect class="glint" x="${CX - 63 - 46}" y="238" width="38" height="46" fill="url(#g-glint)"/></g>`;

/* the leaf sits back in the stone: soft shadow pooled along its edges, deepest under the arch */
const RECESS = `<path d="M${CX - RL} ${BOTTOM} L${CX - RL} ${SPRING} A${RL} ${RL} 0 0 1 ${CX + RL} ${SPRING} L${CX + RL} ${BOTTOM}" fill="none" stroke="#000" stroke-width="20" opacity=".6" filter="url(#soft6)"/>` +
  `<path d="M${CX - RL} ${SPRING} A${RL} ${RL} 0 0 1 ${CX + RL} ${SPRING}" fill="none" stroke="#000" stroke-width="30" opacity=".45" filter="url(#soft14)"/>`;
/* polished plate: brushed grain and a broken specular streak */
const SHEEN = brush => `<g clip-path="url(#plate-clip)">${brush ? `<rect x="${CX - 63}" y="238" width="126" height="46" fill="url(#p-brush)" opacity=".12"/>` : ''}<rect x="${CX - 63}" y="238" width="126" height="46" fill="url(#g-sheen)" opacity=".75"/><rect x="${CX - 63}" y="281" width="126" height="3" fill="#000" opacity=".25"/></g>`;

const LEAF_BEHIND = {dumbledore: fanlight};
const LEAF_FRONT = {snape: grille, mcgonagall: kickPlate, lupin: moonChart, moody: vigilance, umbridge: decree, dumbledore: feather, slughorn: invitation};
Object.keys(EXTRAS).forEach(id => {
  const base = EXTRAS[id];
  EXTRAS[id] = () => (LEAF_BEHIND[id] ? LEAF_BEHIND[id]() : '') + SHEEN(id !== 'umbridge') + base() + (LEAF_FRONT[id] ? LEAF_FRONT[id]() : '') + RECESS + GLINT;
});

/* each stone gets a pillowed face: catch-light on top, shadow gathering underneath */
export function shadeStones(svg){
  return svg
    .replace(/<rect x="([-\d.]+)" y="([-\d.]+)" width="([\d.]+)" height="([\d.]+)" rx="(3\.5|2\.5)" fill="#[0-9a-fA-F]{6}"\/>/g,
      (m, x, y, w, h, rx) => m + `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="url(#g-stone)"/>`)
    .replace(/<polygon points="([^"]+)" fill="#[0-9a-fA-F]{6}" stroke="#0C100E" stroke-width="2.4" stroke-linejoin="round"\/>/g,
      (m, p) => m + `<polygon points="${p}" fill="url(#g-stone)"/>`);
}

/* ============================================================ props around the door (wall, jambs, floor) */

function cobweb(x, y, flip){
  const k = flip ? -1 : 1, P = (dx, dy) => `${r1(x + dx * k)} ${r1(y + dy)}`;
  return `<g stroke="#C9D2CB" stroke-opacity=".2" fill="none" stroke-width=".7"><path d="M${P(0, 0)} L${P(40, 2)} M${P(0, 0)} L${P(34, 26)} M${P(0, 0)} L${P(16, 44)} M${P(0, 0)} L${P(2, 56)}"/>` +
    `<path d="M${P(12, 1)} Q${P(13, 8)} ${P(11, 9)} Q${P(8, 14)} ${P(5, 15)} Q${P(3, 17)} ${P(.5, 18)}"/><path d="M${P(26, 2)} Q${P(25, 15)} ${P(23, 17)} Q${P(15, 28)} ${P(11, 30)} Q${P(5, 37)} ${P(1, 38)}"/><path d="M${P(37, 2)} Q${P(33, 20)} ${P(31, 23)} Q${P(19, 38)} ${P(15, 41)} Q${P(6, 51)} ${P(2, 52)}"/></g>`;
}
function streaks(xs){ return xs.map(([x, y, h, w]) => `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="url(#g-streak)" opacity=".55"/>`).join(''); }
function manacle(x, y){
  return `<rect x="${x - 4}" y="${y - 6}" width="8" height="10" rx="1.5" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".6"/>` +
    `<ellipse cx="${x}" cy="${y + 13}" rx="8.5" ry="10.5" fill="none" stroke="#0E1011" stroke-width="4"/><ellipse cx="${x}" cy="${y + 13}" rx="8.5" ry="10.5" fill="none" stroke="#4A5054" stroke-width="2"/>` +
    `<path d="M${x - 7} ${y + 8} a8.5 10.5 0 0 1 4 -5" stroke="#9AA3A8" stroke-width=".8" fill="none"/>`;
}

/* McGonagall: a silver tabby sitting by the door. Square markings round the eyes; it blinks now and then. */
function tabby(bx, by){
  let s = shadow(bx, by + 1, 22, 3.6);
  const fur = '#8E8A80', dark = '#3E3A34', pale = '#C4BEB0';
  s += `<path d="M${bx + 12} ${by - 3} C${bx + 26} ${by - 2} ${bx + 22} ${by + 3} ${bx + 4} ${by + 1} C${bx - 8} ${by} ${bx - 16} ${by - 1} ${bx - 18} ${by - 6}" stroke="${dark}" stroke-width="7" fill="none" stroke-linecap="round"/>`;
  s += `<path d="M${bx + 12} ${by - 3} C${bx + 26} ${by - 2} ${bx + 22} ${by + 3} ${bx + 4} ${by + 1} C${bx - 8} ${by} ${bx - 16} ${by - 1} ${bx - 18} ${by - 6}" stroke="${fur}" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="4 3"/>`;
  s += `<path d="M${bx - 11} ${by} C${bx - 17} ${by - 10} ${bx - 16} ${by - 32} ${bx - 8} ${by - 40} Q${bx} ${by - 46} ${bx + 8} ${by - 40} C${bx + 16} ${by - 32} ${bx + 17} ${by - 10} ${bx + 11} ${by} Z" fill="${fur}" stroke="${dark}" stroke-width=".7"/>`;
  s += `<path d="M${bx - 14} ${by - 20} q4 -2 7 1 M${bx - 15} ${by - 12} q4 -2 7 1 M${bx + 14} ${by - 20} q-4 -2 -7 1 M${bx + 15} ${by - 12} q-4 -2 -7 1 M${bx - 12} ${by - 28} q3 -2 6 0 M${bx + 12} ${by - 28} q-3 -2 -6 0" stroke="${dark}" stroke-width="1.4" fill="none" stroke-linecap="round"/>`;
  s += `<ellipse cx="${bx}" cy="${by - 18}" rx="6" ry="13" fill="${pale}" opacity=".75"/>`;
  s += `<path d="M${bx - 5} ${by} v-13 M${bx + 5} ${by} v-13" stroke="${dark}" stroke-width=".7" opacity=".7"/><path d="M${bx - 8} ${by} h6 M${bx + 2} ${by} h6" stroke="${pale}" stroke-width="2" stroke-linecap="round"/>`;
  const hy = by - 49;
  s += `<path d="M${bx - 10} ${hy - 4} L${bx - 9} ${hy - 15} L${bx - 3} ${hy - 8} Z M${bx + 10} ${hy - 4} L${bx + 9} ${hy - 15} L${bx + 3} ${hy - 8} Z" fill="${fur}" stroke="${dark}" stroke-width=".7"/>`;
  s += `<path d="M${bx - 8.6} ${hy - 6} L${bx - 8.2} ${hy - 11.5} L${bx - 5} ${hy - 8} Z M${bx + 8.6} ${hy - 6} L${bx + 8.2} ${hy - 11.5} L${bx + 5} ${hy - 8} Z" fill="#7A5A58"/>`;
  s += `<ellipse cx="${bx}" cy="${hy}" rx="11.5" ry="9.6" fill="${fur}" stroke="${dark}" stroke-width=".7"/>`;
  s += `<path d="M${bx - 4} ${hy - 6} l1.3 -2.6 l1.4 2 l1.3 -2 l1.4 2 l1.3 -2.6" stroke="${dark}" stroke-width=".9" fill="none"/>`;
  s += `<path d="M${bx - 11} ${hy + 1} h4 M${bx - 11} ${hy + 3.4} h3.6 M${bx + 11} ${hy + 1} h-4 M${bx + 11} ${hy + 3.4} h-3.6" stroke="${dark}" stroke-width=".8"/>`;
  s += `<rect x="${bx - 8.4}" y="${hy - 3.6}" width="6.6" height="5.2" rx="1.2" fill="none" stroke="${dark}" stroke-width=".9" opacity=".8"/><rect x="${bx + 1.8}" y="${hy - 3.6}" width="6.6" height="5.2" rx="1.2" fill="none" stroke="${dark}" stroke-width=".9" opacity=".8"/><path d="M${bx - 1.8} ${hy - 1.6} h3.6" stroke="${dark}" stroke-width=".7" opacity=".8"/>`;
  s += `<g class="blink"><ellipse cx="${bx - 5.1}" cy="${hy - 1}" rx="2.3" ry="1.7" fill="#D7CF52"/><ellipse cx="${bx + 5.1}" cy="${hy - 1}" rx="2.3" ry="1.7" fill="#D7CF52"/>` +
    `<rect x="${bx - 5.5}" y="${hy - 2.6}" width=".8" height="3.2" rx=".4" fill="#111"/><rect x="${bx + 4.7}" y="${hy - 2.6}" width=".8" height="3.2" rx=".4" fill="#111"/>` +
    `<circle cx="${bx - 4.4}" cy="${hy - 1.8}" r=".55" fill="#fff"/><circle cx="${bx + 5.8}" cy="${hy - 1.8}" r=".55" fill="#fff"/></g>`;
  s += `<path d="M${bx - 1.3} ${hy + 3} h2.6 l-1.3 1.5 Z" fill="#B07A78"/><path d="M${bx} ${hy + 4.5} q-1.6 2 -3.2 1 M${bx} ${hy + 4.5} q1.6 2 3.2 1" stroke="${dark}" stroke-width=".6" fill="none"/>`;
  s += `<path d="M${bx - 4} ${hy + 4} l-12 -1.6 M${bx - 4} ${hy + 5} l-12 1.4 M${bx + 4} ${hy + 4} l12 -1.6 M${bx + 4} ${hy + 5} l12 1.4" stroke="#E8E4DA" stroke-width=".4" opacity=".7"/>`;
  return s;
}

/* Lupin: a battered leather suitcase against the jamb, a half-eaten bar of chocolate on it */
function suitcase(x, by){
  const w = 58, h = 38, y = by - h; let s = `<g transform="rotate(-3 ${x + w / 2} ${by})">` + shadow(x + w / 2, by + 1, w / 2 + 3, 3.5);
  s += `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="4" fill="#5E3F26" stroke="#2A1A0D" stroke-width=".9"/>`;
  s += `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="4" filter="url(#grain)" opacity=".35"/>`;
  s += `<rect x="${x + 1}" y="${y + 1}" width="${w - 2}" height="2" fill="#fff" opacity=".12"/><path d="M${x + 2} ${y + 7} h${w - 4}" stroke="#2A1A0D" stroke-width=".9" opacity=".8"/>`;
  s += `<rect x="${x + 24}" y="${y + 15}" width="16" height="12" fill="#7A5A3A" stroke="#2A1A0D" stroke-width=".6"/><path d="M${x + 25.5} ${y + 16.5} h13 v9 h-13 Z" fill="none" stroke="#C7B08A" stroke-width=".5" stroke-dasharray="1.4 1.2" opacity=".8"/>`;
  [x + 11, x + 44].forEach(sx => {
    s += `<rect x="${sx}" y="${y}" width="6" height="${h}" fill="#3A2614"/><rect x="${sx}" y="${y}" width="1.2" height="${h}" fill="#fff" opacity=".1"/>`;
    s += `<rect x="${sx - 1}" y="${y + 17}" width="8" height="7" rx="1" fill="none" stroke="url(#g-brass)" stroke-width="1.6"/>`; });
  [[x, y, 1, 1], [x + w, y, -1, 1], [x, by, 1, -1], [x + w, by, -1, -1]].forEach(([cx, cy, dx, dy]) => {
    s += `<path d="M${cx} ${cy + 7 * dy} L${cx} ${cy} L${cx + 7 * dx} ${cy} Z" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".5"/>`; });
  s += `<path d="M${x + 22} ${y} q0 -9 7 -9 q7 0 7 9" fill="none" stroke="#2A1A0D" stroke-width="3.6"/><path d="M${x + 22} ${y} q0 -9 7 -9 q7 0 7 9" fill="none" stroke="#6E4A2C" stroke-width="2"/>`;
  s += `<path d="M${x + 6} ${y + 30} l9 2 M${x + 48} ${y + 12} l5 5" stroke="#C7B08A" stroke-width=".7" opacity=".5"/>`;
  const cx0 = x + 3, cy0 = y - 6;
  s += `<rect x="${cx0}" y="${cy0}" width="20" height="6" rx="1" fill="#4A2A18" stroke="#24130A" stroke-width=".5"/><path d="M${cx0 + 5} ${cy0} v6 M${cx0 + 10} ${cy0} v6 M${cx0 + 15} ${cy0} v6" stroke="#24130A" stroke-width=".5"/>`;
  s += `<path d="M${cx0 + 9} ${cy0 - .4} l3 -1.4 l2 1.2 l3 -1.6 l3 1.4 v7 h-11 Z" fill="#B9BEC2" opacity=".9"/><path d="M${cx0 + 12} ${cy0 - .2} h8 v6.6 h-8 Z" fill="#5B2A6E"/>`;
  return s + '</g>';
}

/* Moody: a heavy chain slung across the door, a padlock, a hip flask, a scorch on the flags */
function chain(){
  const x0 = 40, x1 = 210, y0 = 268, sag = 44, mid = (x0 + x1) / 2, half = (x1 - x0) / 2; let s = '';
  const Y = x => y0 + sag * (1 - ((x - mid) / half) ** 2), slope = x => -2 * sag * (x - mid) / (half * half);
  [x0, x1].forEach(x => { s += `<rect x="${x - 5}" y="${y0 - 6}" width="10" height="12" rx="2" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".6"/><circle cx="${x}" cy="${y0}" r="3.4" fill="none" stroke="#0E1011" stroke-width="2.4"/><circle cx="${x}" cy="${y0}" r="3.4" fill="none" stroke="#5A6064" stroke-width="1"/>`; });
  let k = 0;
  for (let x = x0 + 5; x < x1 - 3; x += 8.6, k++){
    const y = Y(x), a = Math.atan(slope(x)) * 180 / Math.PI;
    if (k % 2 === 0) s += `<ellipse cx="${r1(x)}" cy="${r1(y)}" rx="5.6" ry="3" transform="rotate(${r1(a)} ${r1(x)} ${r1(y)})" fill="none" stroke="#0E1011" stroke-width="2.8"/><ellipse cx="${r1(x)}" cy="${r1(y)}" rx="5.6" ry="3" transform="rotate(${r1(a)} ${r1(x)} ${r1(y)})" fill="none" stroke="#5A6064" stroke-width="1.1"/>`;
    else s += `<g transform="rotate(${r1(a)} ${r1(x)} ${r1(y)})"><path d="M${r1(x - 5)} ${r1(y)} h10" stroke="#0E1011" stroke-width="3.6" stroke-linecap="round"/><path d="M${r1(x - 5)} ${r1(y)} h10" stroke="#4A5054" stroke-width="1.8" stroke-linecap="round"/><path d="M${r1(x - 4)} ${r1(y - .6)} h8" stroke="#9AA3A8" stroke-width=".5"/></g>`;
  }
  const py = Y(mid) + 3;
  s += `<path d="M${mid - 8} ${py + 12} V${py + 6} a8 8 0 0 1 16 0 V${py + 12}" fill="none" stroke="#0E1011" stroke-width="4.4"/><path d="M${mid - 8} ${py + 12} V${py + 6} a8 8 0 0 1 16 0 V${py + 12}" fill="none" stroke="#6E7579" stroke-width="2.2"/>`;
  s += `<rect x="${mid - 14}" y="${py + 10}" width="28" height="24" rx="3.5" fill="#000" opacity=".4" transform="translate(1.5 2)"/><rect x="${mid - 14}" y="${py + 10}" width="28" height="24" rx="3.5" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".8"/>`;
  s += `<rect x="${mid - 12}" y="${py + 11.5}" width="24" height="1.4" fill="#9AA3A8" opacity=".5"/><circle cx="${mid}" cy="${py + 21}" r="5" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".6"/><circle cx="${mid}" cy="${py + 20}" r="1.6" fill="#0A0A0A"/><path d="M${mid - .9} ${py + 20.5} h1.8 l.6 4.4 h-3 Z" fill="#0A0A0A"/>`;
  [[mid - 10, py + 14], [mid + 10, py + 14], [mid - 10, py + 30], [mid + 10, py + 30]].forEach(p => { s += `<circle cx="${p[0]}" cy="${p[1]}" r="1.2" fill="#0E1011"/><circle cx="${p[0] - .3}" cy="${p[1] - .3}" r=".45" fill="#9AA3A8"/>`; });
  return s;
}
function flask(x, by){
  let s = shadow(x, by + 1, 11, 2.6);
  s += `<path d="M${x - 8} ${by} V${by - 17} q0 -5 5 -6 h6 q5 1 5 6 V${by} Z" fill="url(#g-pewter)" stroke="#2A2E30" stroke-width=".7"/>`;
  s += `<rect x="${x - 3}" y="${by - 28}" width="6" height="5" rx="1" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".5"/><path d="M${x - 5.6} ${by - 2} V${by - 16}" stroke="#fff" stroke-width="1.2" opacity=".55"/>`;
  s += `<rect x="${x - 4.5}" y="${by - 14}" width="9" height="7" rx="1" fill="none" stroke="#5A6064" stroke-width=".6"/>`;
  return s;
}

/* Umbridge: more kitten plates on the jambs, a lace-edged mat */
function kittenPlate(cx, cy, r, coat, collar){
  const k = r / 23; let s = '';
  s += `<path d="M${cx} ${cy - r - 9} L${cx - r * .7} ${cy - r * .7} M${cx} ${cy - r - 9} L${cx + r * .7} ${cy - r * .7}" stroke="#8A7A55" stroke-width=".6"/>` + nail(cx, cy - r - 9);
  s += `<circle cx="${cx}" cy="${cy + 1.5}" r="${r}" fill="#000" opacity=".25"/><circle cx="${cx}" cy="${cy}" r="${r}" fill="#FBF4F5" stroke="#C9A24A" stroke-width="${r1(1.6 * k + .4)}"/>`;
  s += `<circle cx="${cx}" cy="${cy}" r="${r1(r * .76)}" fill="none" stroke="#E7A9BC" stroke-width=".9" stroke-dasharray="1.6 2"/>`;
  s += `<g transform="translate(${cx} ${cy}) scale(${r1(k * 100) / 100})">`;
  s += `<ellipse cx="0" cy="8" rx="8.5" ry="6.5" fill="${coat}"/><circle cx="0" cy="-2.5" r="7" fill="${coat}"/><path d="M-6.4 -5.5 l1 -7.5 l5 4.6 Z M6.4 -5.5 l-1 -7.5 l-5 4.6 Z" fill="${coat}"/>`;
  s += `<circle cx="-2.6" cy="-3.2" r="1" fill="#2A2118"/><circle cx="2.6" cy="-3.2" r="1" fill="#2A2118"/><path d="M-5 3 l5 2.4 l5 -2.4 l-1.2 4.6 l-3.8 -1.6 l-3.8 1.6 Z" fill="${collar}"/></g>`;
  return s;
}
function laceMat(cx, cy){
  let s = shadow(cx, cy + 3, 76, 13, .35);
  s += `<ellipse cx="${cx}" cy="${cy}" rx="74" ry="13" fill="#D97A9A"/>`;
  for (let a = 0; a < 360; a += 10){ const t = a * Math.PI / 180; s += `<circle cx="${r1(cx + 74 * Math.cos(t))}" cy="${r1(cy + 13 * Math.sin(t))}" r="3.2" fill="#FBEFF2" opacity=".95"/>`; }
  s += `<ellipse cx="${cx}" cy="${cy}" rx="66" ry="10.4" fill="#F3B6CA"/><ellipse cx="${cx}" cy="${cy}" rx="58" ry="8.2" fill="none" stroke="#FBEFF2" stroke-width=".8" stroke-dasharray="2 2"/>`;
  s += `<text x="${cx}" y="${(cy + 4) * 2}" transform="scale(1 .5)" text-anchor="middle" font-family="'IM Fell English', Georgia, serif" font-style="italic" font-size="15" fill="#9A3F62" opacity=".85">Welcome</text>`;
  return s;
}

/* Dumbledore: gold-inlaid signs on the arch stones that breathe with light, a dish of lemon sweets, rising motes */
function archSigns(){
  const glyphs = [
    (x, y) => `<circle cx="${x}" cy="${y}" r="4.4" fill="none"/><circle cx="${x}" cy="${y}" r=".9"/>`,
    (x, y) => `<path d="M${x + 1.5} ${y - 4.6} A4.6 4.6 0 1 0 ${x + 1.5} ${y + 4.6} A3.4 4.6 0 1 1 ${x + 1.5} ${y - 4.6} Z" fill="none"/>`,
    (x, y) => `<path d="${star4(x, y, 5)}" fill="none"/>`,
    (x, y) => `<path d="M${x} ${y - 5} L${x + 4.6} ${y + 3.4} L${x - 4.6} ${y + 3.4} Z M${x - 3.4} ${y + .6} h6.8" fill="none"/>`,
    (x, y) => `<path d="M${x - 4.6} ${y - 3.4} L${x + 4.6} ${y - 3.4} L${x} ${y + 4.6} Z" fill="none"/>`
  ];
  let s = '';
  for (let j = 0; j < 11; j++){
    const a = Math.PI - (j + .5) * Math.PI / 11, key = j === 5, r = key ? 108 : 100;
    const x = r1(CX + r * Math.cos(a)), y = r1(SPRING - r * Math.sin(a));
    let g;
    if (key){ const pts = []; for (let i = 0; i < 16; i++){ const t = i * Math.PI / 8 - Math.PI / 2, rr = i % 2 ? 3.2 : 8; pts.push(r1(x + rr * Math.cos(t)) + ',' + r1(y + rr * Math.sin(t))); } g = `<polygon points="${pts.join(' ')}" fill="none"/>`; }
    else g = glyphs[j % glyphs.length](x, y);
    s += `<g stroke="#4A3608" stroke-width="2.4" fill="#4A3608" stroke-linejoin="round">${g}</g>`;
    s += `<g class="rune" style="animation-delay:-${r1(j * .7)}s" stroke="#F0D688" stroke-width="1.1" fill="#F0D688" stroke-linejoin="round">${g}</g>`;
  }
  return s;
}
function lemonDish(cx, by){
  let s = shadow(cx, by + 2, 23, 3.6);
  s += `<path d="M${cx - 21} ${by - 10} Q${cx - 18} ${by + 1} ${cx} ${by + 1} Q${cx + 18} ${by + 1} ${cx + 21} ${by - 10} Z" fill="url(#g-pewter)" stroke="#2A2E30" stroke-width=".6"/>`;
  s += `<path d="M${cx - 6} ${by + 1} h12 l2 3 h-16 Z" fill="url(#g-pewter)" stroke="#2A2E30" stroke-width=".5"/>`;
  s += `<path d="M${cx - 17} ${by - 7} Q${cx - 14} ${by - 2} ${cx - 7} ${by - 1}" stroke="#fff" stroke-width="1" opacity=".6" fill="none"/>`;
  s += `<ellipse cx="${cx}" cy="${by - 10}" rx="21" ry="4.4" fill="#22262A" stroke="#D9DEE2" stroke-width=".9"/>`;
  [[-10, -12], [0, -13], [10, -12], [-5, -17], [5, -17], [0, -21]].forEach(([dx, dy]) => {
    s += `<ellipse cx="${cx + dx}" cy="${by + dy}" rx="5" ry="3.8" fill="#EFCB2E" stroke="#B8901A" stroke-width=".6"/><ellipse cx="${cx + dx - 1.6}" cy="${by + dy - 1.3}" rx="1.6" ry="1" fill="#FFF6C8" opacity=".85"/>`; });
  s += `<g fill="#fff" opacity=".8"><circle cx="${cx - 3}" cy="${by - 15}" r=".4"/><circle cx="${cx + 7}" cy="${by - 19}" r=".35"/><circle cx="${cx - 9}" cy="${by - 10}" r=".35"/></g>`;
  const wx = cx - 32, wy = by + 2;
  s += shadow(wx, wy + 2, 9, 1.8, .35) + `<path d="M${wx - 4} ${wy} l-5 -3.4 l1 6.6 Z M${wx + 4} ${wy} l5 -3.4 l-1 6.6 Z" fill="#FFF6C8" opacity=".7" stroke="#C9B26A" stroke-width=".4"/><ellipse cx="${wx}" cy="${wy}" rx="4.6" ry="3.4" fill="#EFCB2E" stroke="#B8901A" stroke-width=".6"/><ellipse cx="${wx - 1.4}" cy="${wy - 1.2}" rx="1.4" ry=".9" fill="#FFF6C8" opacity=".8"/>`;
  return s;
}
function motes(seed, color, n, box){
  const R = rng(seed); let s = '';
  for (let i = 0; i < n; i++){ const x = box[0] + R() * (box[2] - box[0]), y = box[1] + R() * (box[3] - box[1]);
    s += `<circle class="mote" style="--dx:${r1((R() - .5) * 24)}px;animation-delay:-${r1(R() * 7)}s;animation-duration:${r1(5 + R() * 4)}s" cx="${r1(x)}" cy="${r1(y)}" r="${r1(.7 + R() * 1)}" fill="${color}"/>`; }
  return s;
}

/* Slughorn: velvet rope on brass posts — members only */
function velvetRope(){
  const xa = 20, xb = 230, by = 552, top = 472; let s = '';
  const post = x => shadow(x, by + 1, 13, 3) +
    `<ellipse cx="${x}" cy="${by - 1}" rx="11" ry="3.6" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".7"/>` +
    `<rect x="${x - 2.8}" y="${top + 6}" width="5.6" height="${by - top - 7}" fill="url(#g-brass-h)" stroke="#6A5218" stroke-width=".5"/>` +
    `<ellipse cx="${x}" cy="${top + 7}" rx="5.4" ry="2" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".5"/>` +
    `<circle cx="${x}" cy="${top}" r="6.4" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".7"/><circle cx="${x - 2}" cy="${top - 2}" r="1.8" fill="#FFF1C2" opacity=".75"/>`;
  s += post(xa) + post(xb);
  const d = `M${xa + 5} ${top + 10} Q${(xa + xb) / 2} ${top + 66} ${xb - 5} ${top + 10}`;
  s += `<path d="${d}" stroke="#000" stroke-width="8" fill="none" opacity=".35" transform="translate(1 3)"/><path d="${d}" stroke="#3A0E2E" stroke-width="7.4" fill="none" stroke-linecap="round"/><path d="${d}" stroke="#7A1F5C" stroke-width="5" fill="none" stroke-linecap="round"/><path d="${d}" stroke="#C46AA0" stroke-width="1.3" fill="none" opacity=".55" transform="translate(0 -1.6)"/>`;
  [xa + 5, xb - 5].forEach(x => { s += `<rect x="${x - 3.6}" y="${top + 6}" width="7.2" height="8" rx="1.6" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".6"/>`; });
  return s;
}

const FRONT = {
  snape: () => cobweb(4, 96, false) + streaks([[13, 226, 120, 5], [24, 300, 150, 3.5], [228, 240, 170, 4]]) + manacle(227, 300) +
    `<ellipse cx="52" cy="537" rx="24" ry="4.6" fill="#0E2A1B" opacity=".85"/><ellipse class="glow" cx="50" cy="536" rx="15" ry="2.2" fill="#3FA66B" opacity=".35"/><path d="M40 535 q8 -1.6 16 0" stroke="#A7E2BF" stroke-width=".6" opacity=".45" fill="none"/>`,
  mcgonagall: () => tabby(27, 548),
  lupin: () => suitcase(186, 551),
  moody: () => `<ellipse cx="190" cy="534" rx="26" ry="7" fill="#000" opacity=".32"/><ellipse cx="186" cy="533" rx="14" ry="3.6" fill="#000" opacity=".3"/>` + chain() + flask(26, 549),
  umbridge: () => kittenPlate(22.5, 300, 12.5, '#D99A5B', '#7FB3D5') + kittenPlate(227.5, 300, 12.5, '#E9E4DE', '#D9618A') + kittenPlate(227.5, 404, 10.5, '#6E6870', '#E8D98A') + laceMat(CX, 530),
  dumbledore: () => archSigns() + lemonDish(214, 546) + motes(77, '#F7E7B0', 14, [30, 140, 220, 480]),
  slughorn: () => velvetRope()
};

export function doorFull(cfg, i){
  const svg = shadeStones(door(cfg, i));
  const front = FRONT[cfg.id] ? FRONT[cfg.id]() : '';
  return svg.replace(/<\/svg>$/, front + '</svg>');
}

/* ============================================================ corridor wall: floating candles, wall torches */

export function floatCandle(x, y, h, k){
  return `<g class="float" style="animation-delay:-${r1((k * 1.37) % 5)}s;animation-duration:${5 + (k % 3)}s">` +
    `<circle class="glow" cx="${x}" cy="${y - 8}" r="30" fill="url(#g-lamp)" opacity=".75"/>` +
    `<rect x="${x - 3.2}" y="${y}" width="6.4" height="${h}" rx="1.2" fill="#EFE6CF"/><rect x="${x - 3.2}" y="${y}" width="1.8" height="${h}" fill="#fff" opacity=".45"/><rect x="${x + 1.6}" y="${y}" width="1.6" height="${h}" fill="#000" opacity=".14"/>` +
    `<path d="M${x - 3.2} ${y + 1} q-1.6 4 0 8 q1.2 1 1.4 -2 Z M${x + 3.2} ${y + 1} q1.2 3 0 5 Z" fill="#EFE6CF"/>` +
    `<path d="M${x} ${y} v-3" stroke="#2A2118" stroke-width="1"/>` +
    `<path class="flame" d="M${x} ${y - 15} q4.6 6 2.6 10 q-1.2 2.6 -2.6 2.6 q-1.4 0 -2.6 -2.6 q-2 -4 2.6 -10 Z" fill="#F08A1D"/>` +
    `<path class="flame" d="M${x} ${y - 10} q2.2 3.4 1.2 5.8 q-.6 1.4 -1.2 1.4 q-.6 0 -1.2 -1.4 q-1 -2.4 1.2 -5.8 Z" fill="#FFF3CF"/></g>`;
}
export function sconce(x, y){
  let s = `<circle class="glow" cx="${x}" cy="${y - 26}" r="74" fill="url(#g-lamp)"/>`;
  s += `<rect x="${x - 8}" y="${y - 2}" width="16" height="30" rx="2" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".7"/>` + nail(x, y + 4) + nail(x, y + 22);
  s += `<path d="M${x} ${y + 14} q14 0 14 -14 v-4" fill="none" stroke="#0E1011" stroke-width="4"/><path d="M${x} ${y + 14} q14 0 14 -14 v-4" fill="none" stroke="#4A5054" stroke-width="1.6"/>`;
  s += `<path d="M${x + 6} ${y - 6} L${x + 9} ${y + 32} L${x + 19} ${y + 32} L${x + 22} ${y - 6} Z" fill="#5A3B22" stroke="#2E1D10" stroke-width=".7"/><path d="M${x + 13} ${y - 4} l1 34" stroke="#2E1D10" stroke-width=".7" opacity=".7"/>`;
  s += `<ellipse cx="${x + 14}" cy="${y - 4}" rx="9.5" ry="3" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".6"/>`;
  s += `<rect x="${x + 6}" y="${y - 17}" width="16" height="13" rx="3" fill="#3A2413"/><path d="M${x + 6} ${y - 13} h16 M${x + 6} ${y - 9} h16" stroke="#1E1209" stroke-width="1"/>`;
  const fx = x + 14, fy = y - 15;
  s += `<path class="flame" style="animation-duration:1.1s" d="M${fx} ${fy - 30} q12 14 8 24 q-3 7 -8 7 q-5 0 -8 -7 q-4 -10 8 -24 Z" fill="#E0701A"/>`;
  s += `<path class="flame" style="animation-duration:1.4s;animation-delay:-.4s" d="M${fx} ${fy - 22} q8 10 5 17 q-2 5 -5 5 q-3 0 -5 -5 q-3 -7 5 -17 Z" fill="#F2B24C"/>`;
  s += `<path class="flame" style="animation-duration:1.7s" d="M${fx} ${fy - 12} q4 6 2.4 9 q-1 2.4 -2.4 2.4 q-1.4 0 -2.4 -2.4 q-1.6 -3 2.4 -9 Z" fill="#FFF3CF"/>`;
  s += `<circle class="spark" style="animation-delay:-.6s" cx="${fx - 2}" cy="${fy - 28}" r=".9" fill="#FFD98A"/><circle class="spark" style="animation-delay:-1.7s" cx="${fx + 3}" cy="${fy - 26}" r=".7" fill="#FFD98A"/>`;
  return s;
}

/* ============================================================ classroom pieces */

/* a cauldron over a log fire: swirling green surface, bubbles that rise and pop, steam */
export function cauldron(){
  const cx = 150; let s = `<defs>
    <radialGradient id="cz-pot" cx=".34" cy=".3" r=".8"><stop offset="0" stop-color="#5A6266"/><stop offset=".35" stop-color="#2A2E30"/><stop offset="1" stop-color="#0B0C0D"/></radialGradient>
    <radialGradient id="cz-liq" cx=".5" cy=".5" r=".6"><stop offset="0" stop-color="#9BE3B4"/><stop offset=".45" stop-color="#3FA66B"/><stop offset="1" stop-color="#14402A"/></radialGradient>
    <radialGradient id="cz-fire" cx=".5" cy=".5" r=".5"><stop offset="0" stop-color="#F2B24C" stop-opacity=".7"/><stop offset="1" stop-color="#F2B24C" stop-opacity="0"/></radialGradient>
    <radialGradient id="cz-mist" cx=".5" cy=".5" r=".5"><stop offset="0" stop-color="#3FA66B" stop-opacity=".45"/><stop offset="1" stop-color="#3FA66B" stop-opacity="0"/></radialGradient>
    <clipPath id="cz-surf"><ellipse cx="${cx}" cy="104" rx="73" ry="12.5"/></clipPath></defs>`;
  s += `<ellipse cx="${cx}" cy="226" rx="120" ry="10" fill="#000" opacity=".5"/>`;
  s += `<ellipse class="glow" cx="${cx}" cy="208" rx="110" ry="34" fill="url(#cz-fire)"/>`;
  s += `<g transform="rotate(-9 ${cx} 214)"><rect x="${cx - 70}" y="207" width="140" height="13" rx="6.5" fill="#4A2C17"/><rect x="${cx - 70}" y="207" width="140" height="3" rx="1.5" fill="#7A5532" opacity=".7"/><ellipse cx="${cx + 69}" cy="213.5" rx="3.6" ry="6.5" fill="#B08654"/><ellipse cx="${cx + 69}" cy="213.5" rx="1.8" ry="3.4" fill="none" stroke="#6E4A2C" stroke-width=".7"/></g>`;
  s += `<g transform="rotate(10 ${cx} 214)"><rect x="${cx - 66}" y="208" width="132" height="12" rx="6" fill="#3E2412"/><rect x="${cx - 66}" y="208" width="132" height="2.6" rx="1.3" fill="#6E4A2C" opacity=".7"/><ellipse cx="${cx - 65}" cy="214" rx="3.4" ry="6" fill="#A87C4C"/></g>`;
  [[-30, 210, 2.4], [-12, 214, 1.8], [8, 211, 2.6], [26, 215, 1.9], [40, 209, 1.5], [-42, 214, 1.6]].forEach(([dx, y, r], i) => {
    s += `<circle class="glow" style="animation-delay:-${i * .5}s" cx="${cx + dx}" cy="${y}" r="${r}" fill="#F26B1D"/>`; });
  [[-36, 30, 1.2], [-16, 40, 1.5], [6, 44, 1.3], [24, 36, 1.6], [42, 28, 1.1]].forEach(([dx, h, d], i) => {
    const x = cx + dx, y = 210;
    s += `<path class="flame" style="animation-duration:${d}s;animation-delay:-${i * .3}s" d="M${x} ${y - h} q${h * .38} ${h * .5} ${h * .25} ${h * .8} q-${h * .1} ${h * .2} -${h * .25} ${h * .2} q-${h * .15} 0 -${h * .25} -${h * .2} q-${h * .12} -${h * .3} ${h * .25} -${h * .8} Z" fill="${i % 2 ? '#F08A1D' : '#E0701A'}"/>`;
    s += `<path class="flame" style="animation-duration:${d + .3}s" d="M${x} ${y - h * .55} q${h * .18} ${h * .26} ${h * .1} ${h * .42} q-${h * .05} ${h * .1} -${h * .1} ${h * .1} q-${h * .05} 0 -${h * .1} -${h * .1} q-${h * .08} -${h * .16} ${h * .1} -${h * .42} Z" fill="#FFE2A0"/>`; });
  s += `<path d="M${cx - 60} 168 L${cx - 74} 222" stroke="#0E1011" stroke-width="7" stroke-linecap="round"/><path d="M${cx + 60} 168 L${cx + 74} 222" stroke="#0E1011" stroke-width="7" stroke-linecap="round"/><path d="M${cx - 61} 170 L${cx - 73} 218" stroke="#4A5054" stroke-width="1.4"/>`;
  s += `<path d="M${cx - 80} 104 C${cx - 92} 160 ${cx - 50} 200 ${cx} 200 C${cx + 50} 200 ${cx + 92} 160 ${cx + 80} 104 Z" fill="url(#cz-pot)" stroke="#060707" stroke-width="1"/>`;
  s += `<path d="M${cx + 52} 186 C${cx + 74} 172 ${cx + 84} 150 ${cx + 82} 124" stroke="#F2B24C" stroke-width="2.4" fill="none" opacity=".28"/>`;
  s += `<path d="M${cx - 66} 124 C${cx - 70} 150 ${cx - 58} 172 ${cx - 40} 184" stroke="#C9D2CB" stroke-width="3" fill="none" opacity=".16" stroke-linecap="round"/>`;
  for (let k = 0; k < 9; k++){ const t = (k + .5) / 9, x = cx - 74 + t * 148, y = 124 + Math.sin(t * Math.PI) * 6;
    s += `<circle cx="${r1(x)}" cy="${r1(y)}" r="2.2" fill="#0E1011"/><circle cx="${r1(x - .6)}" cy="${r1(y - .6)}" r=".8" fill="#9AA3A8"/>`; }
  s += `<path d="M${cx - 78} 122 C${cx - 30} 133 ${cx + 30} 133 ${cx + 78} 122" stroke="#0E1011" stroke-width="2" fill="none" opacity=".7"/>`;
  s += `<ellipse cx="${cx}" cy="104" rx="84" ry="18" fill="#0C0D0E"/>`;
  s += `<ellipse cx="${cx}" cy="104" rx="73" ry="12.5" fill="url(#cz-liq)"/>`;
  s += `<g clip-path="url(#cz-surf)"><g transform="translate(${cx} 104) scale(1 .17)"><g class="swirl">` +
    `<path d="M0 -10 C40 -60 80 -10 50 30 C20 70 -50 50 -60 0 C-70 -40 -20 -80 30 -70" stroke="#C8F2D6" stroke-width="5" fill="none" opacity=".35"/>` +
    `<path d="M-20 20 C-50 -10 -20 -50 20 -40" stroke="#C8F2D6" stroke-width="3.4" fill="none" opacity=".3"/>` +
    `<path d="M10 50 C60 40 70 0 60 -30" stroke="#1E5E3A" stroke-width="7" fill="none" opacity=".45"/></g></g>`;
  [[-40, 106, 2.6], [-14, 100, 3.4], [12, 108, 2.2], [34, 102, 3], [52, 106, 2], [-58, 104, 1.8]].forEach(([dx, y, r], i) => {
    s += `<circle class="pop" style="animation-delay:-${r1(i * .67)}s;animation-duration:${r1(2.2 + (i % 3) * .5)}s" cx="${cx + dx}" cy="${y}" r="${r}" fill="none" stroke="#C8F2D6" stroke-width=".9"/>`; });
  s += `</g>`;
  s += `<ellipse cx="${cx}" cy="104" rx="84" ry="18" fill="none" stroke="url(#g-iron)" stroke-width="7"/>`;
  s += `<path d="M${cx - 80} 100 C${cx - 50} 86 ${cx + 50} 86 ${cx + 80} 100" stroke="#8A9398" stroke-width="1.1" fill="none" opacity=".55"/>`;
  s += `<g transform="rotate(28 ${cx + 40} 96)"><rect x="${cx + 36}" y="20" width="7" height="84" rx="3" fill="#5A3B22" stroke="#2E1D10" stroke-width=".6"/><rect x="${cx + 37}" y="22" width="1.6" height="80" fill="#fff" opacity=".14"/></g>`;
  s += `<ellipse class="glow" cx="${cx}" cy="88" rx="96" ry="40" fill="url(#cz-mist)"/>`;
  [[-26, 0], [6, 1.3], [30, 2.6]].forEach(([dx, d]) => {
    s += `<path class="steam" style="animation-delay:-${d}s" d="M${cx + dx} 92 c-10 -14 10 -22 0 -36 c-8 -12 8 -20 2 -30" stroke="#D7EEDF" stroke-width="6" stroke-linecap="round" fill="none" opacity="0"/>`; });
  return s;
}

/* small brass bell hung on the board frame; it swings when the line is read aloud */
export function bell(){
  return `<path d="M40 7 H25" stroke="#0E1011" stroke-width="3.4" stroke-linecap="round"/><path d="M40 6.4 H25" stroke="#4A5054" stroke-width="1.2"/>` +
    `<g class="bell-body"><path d="M22 7 v6" stroke="#6A5218" stroke-width="1.6"/><circle cx="22" cy="13" r="3.2" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".6"/>` +
    `<path d="M11.5 33 C11.5 22 13.5 15 22 15 C30.5 15 32.5 22 32.5 33 L36 37 H8 Z" fill="url(#g-brass-h)" stroke="#6A5218" stroke-width=".8"/>` +
    `<path d="M16 19 C14.6 24 14.4 29 14.4 33.5" stroke="#FFF1C2" stroke-width="1.5" fill="none" opacity=".75" stroke-linecap="round"/>` +
    `<ellipse cx="22" cy="37" rx="14" ry="2.8" fill="#8E6A1E" stroke="#6A5218" stroke-width=".7"/><circle cx="22" cy="41" r="2.6" fill="#6A5218"/><circle cx="21.3" cy="40.3" r=".8" fill="#E6CC80"/></g>`;
}

/* the caretaker's key ring on a nail */
export function keyring(){
  const key = (ang, len, m, dark, hi) => `<g transform="rotate(${ang} 30 34)">` +
    `<circle cx="30" cy="${40}" r="5.4" fill="none" stroke="${dark}" stroke-width="3.6"/><circle cx="30" cy="40" r="5.4" fill="none" stroke="${m}" stroke-width="2"/>` +
    `<rect x="28.2" y="45" width="3.6" height="${len}" fill="${m}" stroke="${dark}" stroke-width=".6"/><rect x="27" y="46" width="6" height="2.2" fill="${m}" stroke="${dark}" stroke-width=".5"/>` +
    `<path d="M31.8 ${45 + len - 9} h5 v3 h-2 v2 h2 v4 h-5 Z" fill="${m}" stroke="${dark}" stroke-width=".6"/><path d="M29 46 v${len - 2}" stroke="${hi}" stroke-width=".6" opacity=".7"/></g>`;
  return nail(30, 7) +
    `<g class="ring-swing">` +
    key(24, 26, 'url(#g-iron)', '#0E1011', '#9AA3A8') + key(-4, 34, 'url(#g-brass)', '#6A5218', '#FFF1C2') + key(-30, 22, 'url(#g-iron)', '#0E1011', '#9AA3A8') +
    `<circle cx="30" cy="22" r="13" fill="none" stroke="#0E1011" stroke-width="4.2"/><circle cx="30" cy="22" r="13" fill="none" stroke="#5A6064" stroke-width="2"/><path d="M19 15 a13 13 0 0 1 9 -6" stroke="#B9C1C6" stroke-width=".9" fill="none"/>` +
    `</g>`;
}

/* a wax seal with a pressed monogram */
export function waxSeal(letter, color, seed){
  const R = rng(seed), pts = [];
  for (let i = 0; i < 24; i++){ const a = i / 24 * Math.PI * 2, rr = 30 + R() * 5; pts.push([40 + rr * Math.cos(a), 40 + rr * Math.sin(a)]); }
  let d = '';
  pts.forEach((p, i) => { const q = pts[(i + 1) % pts.length], mx = (p[0] + q[0]) / 2, my = (p[1] + q[1]) / 2; d += (i ? ' Q' : `M${r1(mx)} ${r1(my)} Q`) + `${r1(q[0])} ${r1(q[1])} ${r1((q[0] + pts[(i + 2) % pts.length][0]) / 2)} ${r1((q[1] + pts[(i + 2) % pts.length][1]) / 2)}`; });
  const id = 'ws' + seed;
  return `<defs><radialGradient id="${id}" cx=".36" cy=".3" r=".8"><stop offset="0" stop-color="${shade(color, .35)}"/><stop offset=".55" stop-color="${color}"/><stop offset="1" stop-color="${shade(color, -.45)}"/></radialGradient></defs>` +
    `<path d="${d} Z" fill="#000" opacity=".35" transform="translate(1.5 2.5)"/>` +
    `<path d="M52 66 q2 10 -3 13 q-4 1 -3 -8 Z M24 62 q-4 8 -1 10 q4 0 3 -8 Z" fill="${shade(color, -.15)}"/>` +
    `<path d="${d} Z" fill="url(#${id})"/>` +
    `<circle cx="40" cy="40" r="21" fill="none" stroke="${shade(color, -.45)}" stroke-width="2.4"/><circle cx="40.8" cy="40.8" r="21" fill="none" stroke="${shade(color, .45)}" stroke-width=".8" opacity=".55"/>` +
    `<circle cx="40" cy="40" r="17" fill="none" stroke="${shade(color, -.35)}" stroke-width=".7" stroke-dasharray="1.2 2"/>` +
    `<text x="40.8" y="49.8" text-anchor="middle" font-family="'IM Fell English SC', Georgia, serif" font-size="27" fill="${shade(color, .4)}" opacity=".6">${esc(letter)}</text>` +
    `<text x="40" y="49" text-anchor="middle" font-family="'IM Fell English SC', Georgia, serif" font-size="27" fill="${shade(color, -.5)}">${esc(letter)}</text>` +
    `<path d="M22 24 q8 -8 18 -9" stroke="#fff" stroke-width="1.6" opacity=".28" fill="none" stroke-linecap="round"/>`;
}

/* ink tally marks in fives; each stroke draws in turn */
export function tally(n, seed){
  const R = rng(seed), gw = 36; let s = '';
  for (let i = 0; i < n; i++){
    const g = Math.floor(i / 5), k = i % 5, x0 = g * gw + 5;
    let d;
    if (k < 4){ const x = x0 + k * 6.4 + (R() - .5) * 1.4; d = `M${r1(x)} ${r1(3 + R() * 2)} Q${r1(x + (R() - .5) * 2.4)} 13 ${r1(x + (R() - .5) * 1.6)} ${r1(23 - R() * 2)}`; }
    else d = `M${r1(x0 - 4)} ${r1(18 + R() * 2)} Q${r1(x0 + 10)} ${r1(12 + R() * 2)} ${r1(x0 + 24)} ${r1(6 + R() * 2)}`;
    s += `<path class="ink" style="--i:${i}" pathLength="1" d="${d}" stroke="#2A2118" stroke-width="1.9" fill="none" stroke-linecap="round"/>`;
  }
  return {svg: s, width: Math.max(1, Math.ceil(n / 5)) * gw};
}

/* felt board eraser */
export function eraser(){
  return `<rect x="2" y="2" width="72" height="16" rx="3" fill="url(#g-plank)" stroke="#2E1D10" stroke-width=".8"/><rect x="4" y="3" width="68" height="1.6" fill="#fff" opacity=".2"/>` +
    `<path d="M10 9 h56" stroke="#2E1D10" stroke-width=".6" opacity=".6"/>` +
    `<rect x="3" y="17" width="70" height="10" rx="1.5" fill="#43484B"/><path d="M6 20 h64 M6 23 h64" stroke="#2E3234" stroke-width=".8"/>` +
    `<g fill="#EDEBDD" opacity=".7"><circle cx="12" cy="25" r=".8"/><circle cx="28" cy="26" r="1"/><circle cx="44" cy="25.4" r=".7"/><circle cx="60" cy="26" r=".9"/><rect x="18" y="24" width="22" height="2" opacity=".4"/></g>`;
}

/* a parchment sheet sized to its element: torn edge, stain and fibre, optional dog-ear and brass pin */
export function paperSVG(w, h, seed, opts = {}){
  w = Math.max(40, Math.round(w)); h = Math.max(40, Math.round(h));
  const d = tornRect(w, h, seed, !!opts.top, !!opts.bottom), id = 'pp' + (opts.id || seed);
  /* rag paper: fibrous deckled edge, faint foxing rather than blotches, edges browned with age, a slight curl of light */
  let s = `<svg class="paper" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true">` +
    `<clipPath id="${id}"><path d="${d}"/></clipPath><g filter="url(#deckle)"><path d="${d}" fill="${opts.fill || '#E6D9B8'}"/>` +
    `<g clip-path="url(#${id})"><rect width="${w}" height="${h}" filter="url(#stain)" opacity=".42"/><rect width="${w}" height="${h}" filter="url(#paper)" opacity=".8"/>` +
    `<rect width="${w}" height="${h}" fill="url(#g-curl)"/>` +
    `<path d="${d}" fill="none" stroke="#7A5524" stroke-width="22" opacity=".38" filter="url(#soft6)"/>` +
    `<path d="${d}" fill="none" stroke="#5A3A14" stroke-width="3" opacity=".35" filter="url(#soft3)"/></g></g>`;
  if (opts.fold) s += `<path d="M${w} ${h - 20} L${w} ${h} L${w - 24} ${h} Z" fill="#B9A677"/><path d="M${w} ${h - 20} L${w - 24} ${h}" stroke="#fff" stroke-opacity=".35" stroke-width=".8"/>`;
  if (opts.pin) s += `<circle cx="${w / 2}" cy="11" r="5.5" fill="url(#g-brass)" stroke="#6A5218" stroke-width=".8"/><circle cx="${w / 2 - 1.6}" cy="9.4" r="1.6" fill="#fff" opacity=".55"/>`;
  if (opts.nails) [[14, 14], [w - 14, 14], [14, h - 16], [w - 14, h - 16]].forEach(p => { s += `<circle cx="${p[0] + .8}" cy="${p[1] + 1.2}" r="4" fill="#000" opacity=".3"/><circle cx="${p[0]}" cy="${p[1]}" r="3.8" fill="url(#g-iron)" stroke="#0E1011" stroke-width=".7"/><circle cx="${p[0] - 1}" cy="${p[1] - 1}" r="1.1" fill="#B9C1C6" opacity=".7"/>`; });
  if (opts.pins4) [[16, 12], [w - 16, 12], [16, h - 14], [w - 16, h - 14]].forEach(p => { s += pin(p[0], p[1]); });
  return s + '</svg>';
}

export {esc};
